[package]
name = "kubef"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"

tokio = { version = "1.47.1", features = ["full"] }
kube = { version = "1.1.0", features = ["runtime", "derive", "ws"] }
k8s-openapi = { version = "0.25.0", features = ["latest"] }
figment = { version = "0.10.19", features = ["env", "yaml"] }
serde = "1.0.219"
clap = { version = "4.5.45", features = ["derive"] }
