extend = [{ path = "Makefile.ci.toml" }]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true

[tasks.empty]
disabled = true
private = true

[tasks.init]
private = true

[tasks.end]
private = true
