name: Nix

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    name: Build binary
    if: ${{ github.ref == 'refs/heads/main' || github.event.label.name == 'nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - run: nix build
      - run: ./result/bin/kubef help