name: Nix

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    name: Build binary
    if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.event.label.name == 'nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - run: nix build
      - run: ./result/bin/kubef help